# minimum amount of padding in bases required to evaluate INS events
MIN_INS_PAD <- 300
MIN_SMALL_CNV_PAD <- 1000
MIN_INV_PAD <- 1000
MIN_LARGE_CNV_PAD_PROP <- 0.05

SMALL_CNV_MAX <- 4000
LARGE_CNV_MIN <- 6000

# min and max expected PE sequencing insert size (space between reads)
MIN_INSERT_SIZE <- 300
MAX_INSERT_SIZE <- 700
READ_SIZE <- 150

# minimum amount normalized RD should deviate from 1 to be in support of a CNV
MIN_RD_DEVIATION <- 0.3

# maximum distance from a breakpoint that a PE read alignment can be to be
# evaluated for supporting an event
MAX_PE_BREAKPOINT_DIST <- 500

#' Structural variant evidence files
#'
#' Classes to handle structural variant evidence files used in the GATK-SV
#' pipeline.
#'
#' @details
#' The supported files are almost identical to the ones generated by the GATK
#' tool
#' [CollectSVEvidence](https://gatk.broadinstitute.org/hc/en-us/articles/35967530268443-CollectSVEvidence-BETA)
#' with the main difference being that the files referenced here combine
#' evidence from multiple samples into a single file. All files must be
#' compressed with bgzip and indexed with tabix. Each file/evidence type has a
#' wrapper class that is used to open the file and extract the evidence for a
#' genomic region. Each construction function returns an object of a class with
#' the same name as the constructor.
#'
#' # Paired-end Reads
#'
#' This file contains discordant read pairs and the format is the same as the
#' single sample version, though the "sample name" field may contain multiple
#' samples. An object for this file type can be constructed with the
#' `pe_file()` function.
#'
#' # Split Reads
#'
#' This file contains split read clippings and the format is the same as the
#' single sample version, though the "sample name" field may contain multiple
#' samples. An object for this file type can be constructed with the
#' `sr_file()` function.
#'
#' # Read Depth
#'
#' This file contains binned read depth. The file contains three columns
#' indentifying the interval and then columns, one per sample, of the read
#' depth of reads that start in each interval. There is also a header line that
#' starts with "#Chr", "Start", and "End" in the first three columns and then
#' the sample name of each sample in the file. An object for this file type can
#' be constructed with the `rd_file()`. The read depth file class additionally
#' requires a information on the median read depth of each sample. See
#' [read_median_coverages()].
#'
#' @param path Path to the evidence file.
#' @param medians Named numeric vector of median coverage values of samples.
#' @param cachedir Path to a directory that can be used to store cached files.
#'   It will be created if it does not exist. If `NULL`, the R session
#'   temporary directory will be used.
#' @returns An object for the evidence type.
#'
#' @examples
#' # PE evidence
#'
#' tf_pe_src <- tempfile()
#' tf_pe_dest <- tempfile(fileext = ".gz")
#' src_conn <- file(tf_pe_src, open = "wt")
#' cat("chr14\t10000\t+\tchr14\t20000\t+\tabc0000\n", file = tf_pe_src)
#' cat("chr14\t11000\t+\tchr14\t15000\t+\tabc0000\n", file = tf_pe_src)
#' cat("chr14\t11000\t+\tchr14\t16000\t+\tabc0001\n", file = tf_pe_src)
#' close(src_conn)
#' system2("bgzip", args = c("-c", tf_pe_src), stdout = tf_pe_dest)
#' system2("tabix", args = c("-b", 2, "-e", 2, "-s", 1, tf_pe_dest))
#' pe <- pe_file(tf_pe_dest)
#'
#' # RD evidence
#'
#' tf_medians <- tempfile()
#' writeLines(c("abc0000\tabc0001", "30\t30"), tf_medians)
#' tf_rd_src <- tempfile()
#' tf_rd_dest <- tempfile(fileext = ".gz")
#' src_conn <- file(tf_rd_src, open = "wt")
#' cat("#Chr\tStart\tEnd\tabc0000\tabc0001\n", file = src_conn)
#' cat("chr5\t1000000\t1000100\t40\t41\n", file = src_conn)
#' cat("chr5\t1000100\t1000200\t39\t41\n", file = src_conn)
#' cat("chr5\t1000200\t1000300\t30\t35\n", file = src_conn)
#' close(src_conn)
#'
#' system2("bgzip", args = c("-c", tf_rd_src), stdout = tf_rd_dest)
#' system2("tabix", args = c("-b", 2, "-e", 3, "-s", 1, "-c", "'#'", "-0", tf_rd_dest))
#' rd <- rd_file(tf_rd_dest, tf_medians)
#'
#' @name svevidencefiles
NULL

#' Create a new `svevidence` object
#'
#' This class represents SV evidence over a genomic region. It is assumed that
#' the evidence sources all have the same set of samples.
#'
#' @param contig A string. The contig containing the region.
#' @param start The start of the region (1-start).
#' @param end The end of the region (inclusive).
#' @param pe A [`pe_file`][svevidencefiles] object for the discordant read
#'   pairs evidence.
#' @param sr A [`sr_file`][svevidencefiles] object for the split read evidence.
#' @param rd A [`rd_file`][svevidencefiles] object for the read depth evidence.
#' @param svtype SV type of the variant.
#' @param pad Fraction of region to add as padding when extracting the evidence
#'   in the region. The minimum padded start is 1 and the maximum padded end
#'   is 536870912.
#' @param sr_pad Number of bases to extend the breakpoints of the SV when
#'   querying for SR evidence. `NULL` will use the coordinates from applying
#'   `pad` and an integer value will override `pad` and extend the SV
#'   breakpoints by the given number of bases.
#' @returns A `svevidence` object.
#' @export
#'
#' @examples
#' pe_path <- system.file(
#'     "extdata",
#'     "example.PE.txt.gz",
#'     package = "gorilla",
#'     mustWork = TRUE
#' )
#' sr_path <- system.file(
#'     "extdata",
#'     "example.SR.txt.gz",
#'     package = "gorilla",
#'     mustWork = TRUE
#' )
#' rd_path <- system.file(
#'     "extdata",
#'     "example.RD.txt.gz",
#'     package = "gorilla",
#'     mustWork = TRUE
#' )
#' medians_path <- system.file(
#'     "extdata",
#'     "example_medianCov.txt",
#'     package = "gorilla",
#'     mustWork = TRUE
#' )
#'
#' pe <- pe_file(pe_path)
#' sr <- sr_file(sr_path)
#' rd <- rd_file(rd_path, medians_path)
#'
#' sv <- svevidence("chr16", 28743149, 28745149, pe, sr, rd, "DUP")
svevidence <- function(contig, start, end, pe, sr, rd, svtype, pad = 0, sr_pad = NULL) {
    new_svevidence(contig, start, end, pe, sr, rd, svtype, pad, sr_pad)
}

#' @rdname subset_samples
#' @export
subset_samples.svevidence <- function(x, samples) {
    pe <- subset_samples(x$pe, samples)
    sr <- subset_samples(x$sr, samples)
    rd <- subset_samples(x$rd, samples)

    structure(
        list(
            pe = pe,
            sr = sr,
            rd = rd,
            svtype = x$svtype,
            region = x$region
        ),
        class = "svevidence"
    )
}

#' @export
c.svevidence <- function(...) {
    dots <- list(...)

    if (length(dots) == 0) {
        return(NULL)
    }

    if (length(dots) < 1) {
        return(dots[[1]])
    }

    first_svtype <- dots[[1]]$svtype
    first_region <- dots[[1]]$region
    for (i in seq(2, length(dots))) {
        if (!inherits(dots[[i]], "svevidence")) {
            stop("all objects must be `svevidence`")
        }

        svtype <- dots[[i]]$svtype
        if (dots[[i]]$svtype != first_svtype) {
            stop("only evidence for the same SV type can be merged")
        }

        region <- dots[[i]]$region
        if (!identical(dots[[i]]$region, first_region)) {
            stop("only evidence from the same region can be merged")
        }
    }

    pe <- lapply(dots, \(x) x$pe)
    sr <- lapply(dots, \(x) x$sr)
    rd <- lapply(dots, \(x) x$rd)

    structure(
        list(
            pe = do.call(c, pe),
            sr = do.call(c, sr),
            rd = do.call(c, rd),
            svtype = first_svtype,
            region = first_region
        ),
        class = "svevidence"
    )
}

#' Does an SV have supporting evidence
#'
#' Check the evidence for an SV to see if the call is supported.
#'
#' The method for [`svevidence`] will check if an SV is supported by PE, SR, or
#' RD evidence.
#'
#' @param x Object that can be used to check SV support.
#' @param sample_id ID of sample to check.
#' @returns Does the SV have supporting evidence.
#'
#' @export
supports_sv <- function(x, sample_id) {
    UseMethod("supports_sv")
}

#' @export
supports_sv.svevidence <- function(x, sample_id) {
    stopifnot(is_string(sample_id))

    region <- x$region
    svlen <- region$end - region$start + 1
    start_pad <- region$start - region$qstart
    end_pad <- region$qend - region$end
    # it is assumed that start and end are always fully within qstart and qend
    if (x$svtype == "INS" && (start_pad < MIN_INS_PAD || end_pad < MIN_INS_PAD)) {
        warning(sprintf("INS events require %d bases of padding", MIN_INS_PAD))
        return(NA)
    } else if (x$svtype == "DEL" || x$svtype == "DUP") {
        if (svlen < LARGE_CNV_MIN) {
            if (start_pad < MIN_SMALL_CNV_PAD || end_pad < MIN_SMALL_CNV_PAD) {
                warning(sprintf("CNVs smaller than %d bases require %d bases of padding", LARGE_CNV_MIN, MIN_SMALL_CNV_PAD))
                return(NA)
            }
        } else {
            required_pad <- ceiling(svlen * MIN_LARGE_CNV_PAD_PROP)
            if (start_pad < required_pad || end_pad < required_pad) {
                warning(sprintf("CNVs equal to or larger than %d bases require %d%% padding", LARGE_CNV_MIN, ceiling(MIN_LARGE_CNV_PAD_PROP * 100)))
                return(NA)
            }
        }
    } else if (x$svtype == "INV") {
        if (start_pad < MIN_INV_PAD || end_pad < MIN_INV_PAD) {
            warning(sprintf("INVs events require %d bases of padding", MIN_INV_PAD))
            return(NA)
        }
    } else {
        stop(sprintf("unknown SV type: %s", x$svtype))
    }

    # only the RD matrix has all samples regardless of discordant pairs or
    # split reads
    if (!sample_id %in% colnames(x$rd$mat)) {
        warning(sprintf("'%s' does not have evidence", sample_id))
        return(NA)
    }

    f <- switch(
        x$svtype,
        DUP = check_dup,
        DEL = check_del,
        INV = check_inv,
        INS = check_ins
    )

    f(x, sample_id)
}

# PE evidence
# If the read-pairs span the entire duplication (reference + additional
# segment), then read-pairs will align to reference closer together than
# expected. If one read in the pair is from the duplicated segment and the mate
# is from the duplication, the reads will align in an inverted orientation.
#
# SR evidence
# split reads at the right end of the duplicated segment
#
# RD evidence
# possible increase in read depth
check_dup <- function(x, sample_id) {
    rcontig <- NULL
    mcontig <- NULL
    rstart <- NULL
    mstart <- NULL
    rstrand <- NULL
    mstrand <- NULL

    region <- x$region
    target <- sample_id
    pe_pad <- MAX_PE_BREAKPOINT_DIST
    sample_pe <- x$pe$mat[sample_id == target & rcontig == mcontig, ]

    # LR read pairs
    lr_pe <- sample_pe[rstrand == "+" & mstrand == "-" & abs(rstart + READ_SIZE - region$start) <= pe_pad & abs(mstart - region$end) <= pe_pad, ]
    # RL read pairs
    rl_pe <- sample_pe[rstrand == "-" & mstrand == "+" & abs(rstart - region$start) <= pe_pad & abs(mstart + READ_SIZE - region$end) <= pe_pad, ]
    # LR read pairs closer together than expected
    squished_pe <- lr_pe[mstart - (rstart + READ_SIZE) + 1 < MAX_INSERT_SIZE, ] 
    has_pe_support <- nrow(rl_pe) > 0 || nrow(squished_pe) > 0

    rd_pad <- ceiling((region$end - region$start + 1) * MIN_LARGE_CNV_PAD_PROP)
    rd_start <- region$start - rd_pad
    rd_end <- region$end + rd_pad
    rd <- x$rd
    rd_ranges <- rd$ranges
    intervals <- rd_start <= S4Vectors::end(rd_ranges) & rd_end >= S4Vectors::start(rd_ranges)
    if (any(intervals)) {
        has_rd_support <- median(rd$mat[intervals, target]) >= 1 + MIN_RD_DEVIATION
    } else {
        has_rd_support <- FALSE
    }

    svlen <- region$end - region$start + 1
    if (svlen <= SMALL_CNV_MAX) {
        return(has_pe_support)
    } else if (svlen > SMALL_CNV_MAX && svlen < LARGE_CNV_MIN) {
        return(has_pe_support || has_rd_support)
    } else {
        return(has_rd_support)
    }
}

# PE evidence
# read-pairs align farther apart than expected
#
# SR evidence
# split reads at the delete breakpoints
#
# RD evidence
# possible drop in read depth
check_del <- function(x, sample_id) {
    rcontig <- NULL
    mcontig <- NULL
    rstart <- NULL
    mstart <- NULL
    rstrand <- NULL
    mstrand <- NULL

    region <- x$region
    target <- sample_id
    pe_pad <- MAX_PE_BREAKPOINT_DIST
    sample_pe <- x$pe$mat[sample_id == target & rcontig == mcontig, ]

    lr_pe <- sample_pe[rstrand == "+" & mstrand == "-" & abs(rstart + READ_SIZE - region$start) <= pe_pad & abs(mstart - region$end) <= pe_pad, ]
    # LR read pairs farther apart than expected
    expanded_pe <- lr_pe[mstart - (rstart + READ_SIZE) + 1 > MIN_INSERT_SIZE, ] 
    has_pe_support <- nrow(expanded_pe) > 0

    rd_pad <- ceiling((region$end - region$start + 1) * MIN_LARGE_CNV_PAD_PROP)
    rd_start <- region$start - rd_pad
    rd_end <- region$end + rd_pad
    rd <- x$rd
    rd_ranges <- rd$ranges
    intervals <- rd_start <= S4Vectors::end(rd_ranges) & rd_end >= S4Vectors::start(rd_ranges)
    if (any(intervals)) {
        has_rd_support <- median(rd$mat[intervals, target]) <= 1 - MIN_RD_DEVIATION
    } else {
        has_rd_support <- FALSE
    }

    svlen <- region$end - region$start + 1
    if (svlen <= SMALL_CNV_MAX) {
        return(has_pe_support)
    } else if (svlen > SMALL_CNV_MAX && svlen < LARGE_CNV_MIN) {
        return(has_pe_support || has_rd_support)
    } else {
        return(has_rd_support)
    }
}

# PE evidence
# Read-pairs that cross from the reference segment to the inverted segment will
# align in the wrong orientation (LR to LL or RR).
check_inv <- function(x, sample_id) {
    rcontig <- NULL
    mcontig <- NULL
    rstart <- NULL
    mstart <- NULL
    rstrand <- NULL
    mstrand <- NULL

    region <- x$region
    target <- sample_id
    pad <- MAX_PE_BREAKPOINT_DIST
    sample_pe <- x$pe$mat[sample_id == target & rcontig == mcontig, ]
    # LL read pairs
    ll_pe <- sample_pe[rstrand == "+" & mstrand == "+" & abs(rstart + READ_SIZE - region$start) <= pad & abs(mstart + READ_SIZE - region$end) <= pad, ]
    rr_pe <- sample_pe[rstrand == "-" & mstrand == "-" & abs(rstart - region$start) <= pad & abs(mstart - region$end) <= pad, ]

    nrow(ll_pe) > 0 && nrow(rr_pe) > 0
}

# SR evidence
# split reads around the breakpoint of the insertion
check_ins <- function(x, sample_id) {
    side <- NULL
    pos <- NULL
    count <- NULL

    region <- x$region
    left_pad_start <- region$start - MIN_INS_PAD
    left_pad_end <- region$start + MIN_INS_PAD
    right_pad_start <- region$end - MIN_INS_PAD
    right_pad_end <- region$end + MIN_INS_PAD
    sr <- x$sr$mat[sample_id == sample_id, ]
    left_bp_sr <- sr[pos >= left_pad_start & pos <= left_pad_end & side == "right" & count > 1, ]
    right_bp_sr <- sr[pos >= right_pad_start & pos <= right_pad_end & side == "left" & count > 1, ]

    nrow(left_bp_sr) > 0 && nrow(right_bp_sr) > 0
}

new_svevidence <- function(contig, start, end, pe, sr, rd, svtype, pad, sr_pad) {
    stopifnot(is_string(contig))
    stopifnot(is_number(start))
    stopifnot(is_number(end))
    stopifnot(inherits(pe, "pe_file"))
    stopifnot(inherits(sr, "sr_file"))
    stopifnot(inherits(rd, "rd_file"))
    stopifnot(is_string(svtype))
    stopifnot(is_number(pad) && pad >= 0)
    stopifnot(is.null(sr_pad) || (is_integerish(sr_pad) && sr_pad >= 0))

    pad_size <- ceiling((end - start + 1) * pad)
    qstart <- max(1, start - pad_size)
    qend <- min(TABIX_MAX_SEQLEN, end + pad_size)
    pe_mat <- query(pe, contig, qstart, qend)
    rd_mat <- query(rd, contig, qstart, qend)
    if (!is.null(sr_pad)) {
        srstart <- max(1, start - sr_pad)
        srend <- min(TABIX_MAX_SEQLEN, end + sr_pad)
        sr_mat <- query(sr, contig, srstart, srend)
    } else {
        sr_mat <- query(sr, contig, qstart, qend)
    }
    region <- list(
        contig = contig,
        start = start,
        end = end,
        qstart = qstart,
        qend = qend
    )

    structure(
        list(
            pe = pe_mat,
            sr = sr_mat,
            rd = rd_mat,
            svtype = svtype,
            region = region
        ),
        class = "svevidence"
    )
}
